# Setup
path:
baseurl:      ""
markdown:     kramdown
google_analytics:
github:       libp2p/libp2p-website

# Metadata
title:        libp2p
description:  A network framework for decentralized P2P application development
license:      MIT

# Favicon
favicon:
  mimetype:   image/png
  name:       favicon.png

# Logo
# The mimetype is defined by OGP. See http://ogp.me
# Comment out all of these lines to use title and description in the header
logo:
  name:       logo.png
  mimetype:   image/png
  width:      483
  height:     204

# About/contact
author:
  name:       Protocol Labs Inc.
  url:        https://ipfs.io

# Open Source Protocol
# See http://osprotocol.com
os:
  repo:     https://github.com/libp2p/libp2p-website
  src:      git@github.com:libp2p/libp2p-website.git
  issues:   https://github.com/libp2p/libp2p-website/issues
  branch:   minimal-cayman
  rcs_type: git

# Maintainer (normally on GitHub)
maintainer:
  name: Protocol Labs Inc.
  link: https://github.com/libp2p

# Gems
